In [56]:
import pandas as pd
import numpy as np

In [57]:
# Load dataset

df = pd.read_csv("Luxury_Housing_Bangalore.csv")

In [58]:
df.head(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.896752354445224,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.
7,PROP000008,whitefield,Project_7,Total Environment,5763.0,3BHK,9.357538943683888,Secondary,NRI,2025-03-31,6.781306,9.565013,Under construction,Direct,yes,9.054713,31,NaN
8,PROP000009,sarjapur road,Project_8,Prestige,5815.0,3Bhk,12.299449409872416,Secondary,Other,2024-03-31,7.284164,5.580442,Under construction,NRI Desk,yes,8.552046,68,NaN
9,PROP000010,JP NAGAR,Project_9,Puravankara,8675.0,4Bhk,9.193310278863123,Primary,CXO,2023-09-30,9.964399,7.759907,Launch,Direct,yes,8.395691,18,Too far from my office.

In [59]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [60]:
## shape of data
print("Shape : ",df.shape)

# column info 
df.info()

## Null values 
print("\nNull values:\n",df.isnull().sum())

Shape :  (101000, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

Null values:
 Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [61]:
# booking status distribution
print(df['Transaction_Type'].value_counts())

# unique markets 
print("Micro Market:", df['Micro_Market'].nunique())

# unique builders (Developer_Name in your dataset)
print("Builders:", df['Developer_Name'].nunique())

Transaction_Type
Secondary    50506
Primary      50494
Name: count, dtype: int64
Micro Market: 48
Builders: 11

In [62]:
print(df.columns)

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

Data Cleaning

In [63]:
# clean Ticket_price_cr

df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].astype(str)

In [64]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].str.replace('Cr','',regex=False).str.strip()

In [65]:
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [66]:
df['Ticket_Price_Cr'].dtype

dtype('float64')

In [67]:
## Handle missing value 

df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         28230
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [68]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].median())

In [69]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].median())

df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].fillna(df['Unit_Size_Sqft'].median())

df['Amenity_Score'] = df['Amenity_Score'].fillna(df['Amenity_Score'].median())

df['Buyer_Comments'] = df['Buyer_Comments'].fillna('No comments')

In [70]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

 Feature Engineering

In [71]:
## Booking flag 

df['Booking_Flag'] = df['Transaction_Type'].apply(
    lambda x: 1 if x == 'Primary' else 0
)

In [72]:
df['Booking_Flag'].mean()

np.float64(0.49994059405940594)

In [73]:
df['Booking_Flag'].value_counts()

Booking_Flag
0    50506
1    50494
Name: count, dtype: int64

In [74]:
## price per sqft

df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 10000000) / df['Unit_Size_Sqft']

In [75]:
df['Price_per_Sqft']

0         31679.120594
1         28284.985887
2         13646.976013
3         15175.012103
4         21471.096187
              ...
100995    13258.612265
100996    31776.329690
100997    23839.912923
100998    14679.430230
100999    37398.481329
Name: Price_per_Sqft, Length: 101000, dtype: float64

In [76]:
df['Purchase_Quarter'].unique()

array(['2025-03-31', '2024-06-30', '2023-12-31', '2024-03-31',
       '2024-12-31', '2023-09-30', '2024-09-30', '2023-06-30'],
      dtype=object)

In [77]:
## Quarter Number 

# convert to datetime 
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])

# extract quarter 
df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter

In [78]:
df[['Purchase_Quarter', 'Quarter_Number']].head()

  Purchase_Quarter  Quarter_Number
0       2025-03-31               1
1       2024-06-30               2
2       2023-12-31               4
3       2024-03-31               1
4       2024-12-31               4

In [79]:
## price category 

df['Price_Category'] = pd.cut(
    df['Ticket_Price_Cr'],
    bins=[0, 2, 5, 10, 100],
    labels=['low', 'Mid', 'High', 'Ultra Luxury']
)

In [80]:
## Premium Property

df['Premium_Property'] = df['Amenity_Score'].apply(
    lambda x: 1 if x > 8 else 0
)

In [81]:
# import mysql.connector
import pymysql

In [82]:
mydb = pymysql.connect(
    host = "localhost" ,
    user = "root" ,
    password = "Hariom@1204" 
)

In [83]:
mydb

In [84]:
mycursor = mydb.cursor()

In [85]:
mydb = pymysql.connect(
    host="localhost",
    user="root",
    password="Hariom@1204",
    database="Luxury_housing"
)

print("Connected to MySQL successfully")

Connected to MySQL successfully

In [86]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Hariom%401204@localhost:3306/Luxury_housing"
)

print("Engine connected successfully")

Engine connected successfully

In [87]:
df.to_sql(
    name='housing_data',
    con=engine,
    if_exists='replace',
    index=False
)

101000